# Generated by Django 5.1.3 on 2024-12-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment1',
            old_name='datetime',
            new_name='date',
        ),
    ]
